[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyproject_template"
version = "0.0.1"
authors = [{ name = "Andreas Schreiber", email = "andi@example.com" }]
description = "Just a template"
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = ["numpy", "pandas"]

[tool.setuptools]
package-dir = { "" = "src" }

[project.scripts]
entrypoint = "main:main"

[tool.pytest.ini_options]
testpaths = ["tests/unit_tests"]
