[build-system]
requires = ["setuptools>=62.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyproject_template"
version = "0.0.1"
authors = [{ name = "Andreas Schreiber", email = "andi@example.com" }]
description = "Just a template"
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = ["numpy", "pandas"]

[project.optional-dependencies]
testing = ["pytest", "tox"]

[tool.setuptools]
package-dir = { "" = "src" }

[project.scripts]
entrypoint = "main:main"

[tool.pytest.ini_options]
testpaths = ["tests/unit_tests"]


[tool.tox]
min_version = "3.10.0"
env_list = ["py310", "py311", "py312"]
isolated_build = true

[tool.tox.env.testenv]
set_env = { PYTHONPATH = "{toxinidir}" }
deps = ["pytest"]
commands = ["pytest --basetemp={envtmpdir}"]

[tool.tox.gh.python]
"3.10" = "py310"
"3.11" = "py311"
"3.12" = "py312"
