name: Test with Cache

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ${{ env.Python3_ROOT_DIR }}/lib/python3.8/site-packages
          key: test-packages-${{ hashFiles('**/pyproject.toml') }}-3.8
      - name: Install dependencies
        run: pip install -e .[testing]
      - name: Test with pytest
        run: pytest
