name: Test with Cache

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ${{ env.Python3_ROOT_DIR }}/lib/python3.12/site-packages
          key: test-packages-${{ hashFiles('**/pyproject.toml') }}-3.12
        run: |
          python -m pip install --upgrade pip
          pip install -e .[testing]
      - name: Test with pytest
        run: pytest
